# Generated by Django 4.2.23 on 2026-07-09 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_link', models.URLField()),
                ('file_reference', models.CharField(blank=True, max_length=500)),
                ('time_taken_minutes', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessmentbrief')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='candidates.candidate')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'), models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('candidate', 'assessment'), name='unique_candidate_assessment_submission'),
        ),
    ]
