# Generated by Django 4.2.23 on 2026-07-09 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('BACKEND', 'Backend Developer'), ('FRONTEND', 'Frontend Developer'), ('FULLSTACK', 'Full Stack Developer')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='assessments_role_c967cd_idx'), models.Index(fields=['is_active'], name='assessments_is_acti_51bf42_idx')],
            },
        ),
    ]
