# Generated by Django 4.2.23 on 2026-07-09 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('HOLD', 'Hold')], max_length=10)),
                ('private_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['score'], name='reviews_rev_score_de8593_idx'), models.Index(fields=['decision'], name='reviews_rev_decisio_88dd01_idx')],
            },
        ),
    ]
