# Generated by Django 4.2.23 on 2026-07-09 16:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=20)),
                ('actor_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('SUBMISSION_CREATED', 'Submission Created'), ('SUBMISSION_UPDATED', 'Submission Updated'), ('REVIEW_ADDED', 'Review Added')], max_length=50)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['created_at'], name='audit_logs__created_0fc90a_idx')],
            },
        ),
    ]
